RedRiver.CoffeeMachine.Api/Models/DrinkModel.cs
using RedRiver.CoffeeMachine.Domain;
using RedRiver.CoffeeMachine.Domain.Base;

namespace RedRiver.CoffeeMachine.Api.Models
{
    public class DrinkModel
    {
        public DrinkModel(Drink drink)
        {
            PreparationSteps = drink.PreperationSteps;
        }

        public IList<PreperationStep> PreparationSteps { get; set; }
    }
}

RedRiver.CoffeeMachine.Api/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc;
using RedRiver.CoffeeMachine.Api.Models;
using RedRiver.CoffeeMachine.Processor.Services.ChocolateServices;
using RedRiver.CoffeeMachine.Processor.Services.CoffeeServices;
using RedRiver.CoffeeMachine.Processor.Services.LemonTeaServices;

namespace RedRiverCoffeeMachineApi.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MachineController : Controller
    {
        private readonly ChocolateService _chocolateService;
        private readonly CoffeeService _coffeeService;
        private readonly LemonTeaService _lemonTeaService;

        public MachineController(
            ChocolateService chocolateService,
            CoffeeService coffeeService,
            LemonTeaService lemonTeaService)
        {
            _chocolateService = chocolateService;
            _coffeeService = coffeeService;
            _lemonTeaService = lemonTeaService;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            return View("DrinkSelection");
        }

        [HttpGet]
        [Route("chocolate")]
        public IActionResult GetChocolate()
        {
            var chocolate = _chocolateService.MakeDrink();

            var model = new DrinkModel(chocolate);

            return View("DrinkSelection", model);
        }

        [HttpGet]
        [Route("coffee")]
        public IActionResult GetCoffee()
        {
            var coffee = _coffeeService.MakeDrink();

            var model = new DrinkModel(coffee);

            return View("DrinkSelection", model);
        }

        [HttpGet]
        [Route("lemon_tea")]
        public IActionResult GetLemonTea()
        {
            var lemonTea = _lemonTeaService.MakeDrink();

            var model = new DrinkModel(lemonTea);

            return View("DrinkSelection", model);
        }
    }
}

RedRiver.CoffeeMachine.Api/Views/shared/DrinkSelection.cshtml
@model RedRiver.CoffeeMachine.Api.Models.DrinkModel

<h1>@Resources.DrinkSelectionResources.HeaderText</h1>

<div>@Html.ActionLink(Resources.DrinkSelectionResources.ChocolateButtonText, "GetChocolate", "Machine", null, new { @class = "btn btn-default" })</div>
<div>@Html.ActionLink(Resources.DrinkSelectionResources.CoffeeButtonText, "GetCoffee", "Machine", null, new { @class = "btn btn-default" })</div>
<div>@Html.ActionLink(Resources.DrinkSelectionResources.LemonTeaButtonText, "GetLemonTea", "Machine", null, new { @class = "btn btn-default" })</div>

<div>
    @if(Model?.PreparationSteps != null)
    {
        <h2>@Resources.DrinkSelectionResources.PrepStepsHeaderText</h2>
    
        <ul>
            @foreach(var step in Model.PreparationSteps)
            {
                <li>@step.Description</li>
            }
        </ul>
    }
</div>